apiVersion: v1
kind: Service
metadata:
  annotations:
    ai.clipper.container.label: ""
  creationTimestamp: null
  labels:
    io.kompose.service: query-frontend
  name: query-frontend
spec:
  ports:
  - name: "7000"
    port: 7000
    targetPort: 7000
  - name: "1337"
    port: 1337
    targetPort: 1337
  selector:
    io.kompose.service: query-frontend
status:
  loadBalancer: {}
